          - name: Install MySQL Database
            apt: name='{{item}}' state=present
            with_items:
              - mysql-server
              - mysql-client
              - python-pymysql
              - python-mysqldb

          - name: start MySQL Database service
            service: name=mysql state=started enabled=yes

          - name: update mysql root password for all root accounts
            mysql_user:
              name: root
              host: "{{ item }}"
              login_unix_socket: /var/run/mysqld/mysqld.sock
              password: "{{ db_password }}"
              login_user: root
              login_password: "{{ db_password }}"
              check_implicit_admin: yes
              priv: "*.*:ALL,GRANT"
            with_items:
              - 127.0.0.1
              - ::1
              - localhost

          - name: Create DB
            mysql_db:
              name: "{{ db_name }}"
              state: present
              config_file: /home/osboxes/.my.cnf

          - name: Create DB user
            mysql_user:
              name: "{{ db_user }}"
              password: Passw0rd
              priv: '*.*:ALL'
              state: present
              host: '%'
              config_file: /home/osboxes/.my.cnf
